  # Общая информация о приложении
spring:
  application:
    name: finance-tracker
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  # Основные параметры Spring Boot
  main:
    banner-mode: "off"

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml


  # Конфигурация JPA/Hibernate для PostgreSQL
  jpa:
    open-in-view: false                # Закрывает сессию Hibernate после запроса (избегает N+1 проблем)
    show-sql: true                     # SQL запросы консоль
    hibernate:
      ddl-auto: validate               # Только проверка соответствия схемы БД и сущностей, изменения НЕ вносятся
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25               # Группирует 25 INSERT/UPDATE операций в один батч
          fetch_size: 50               # JDBC загружает 50 строк за раз
          order_inserts: true          # Переупорядочивает INSERT
          order_updates: true          # Переупорядочивает UPDATE
        use_sql_comments: true         # Добавляет комментарии к SQL
        format_sql: false              # SQL не форматируется

  # Конфигурация Jackson для JSON сериализации/десериализации
  jackson:
    serialization:
      indent-output: false             # Без отступов для уменьшения размера JSON
    deserialization:
      fail-on-unknown-properties: false # Игнорирует неизвестные поля при парсинге JSON
    default-property-inclusion: non_null # В JSON включаются только ненулевые поля

  # Конфигурация валидации
  validation:
    enabled: true

  kafka:
    topics:
      large-expense: large-expense-alert
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 3
        spring.json.add.type.headers: true

  # Конфигурация логирования - базовое (в профилях переопределим)
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: logs/application.log

# Конфигурация сервера
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always            # Всегда включает сообщение об ошибке в response
    include-binding-errors: always     # Включает ошибки валидации поле
  tomcat:
    max-http-form-post-size: 1MB
    max-swallow-size: 2MB

  # JWT (JSON Web Token) конфигурация для аутентификации
jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"  # HMAC SHA-256 ключ (не менее 256 бит)
  expiration: 86400000                                                        # Токен истекает через 24 часа

admin:
  email: ${ADMIN_EMAIL:admin@example.com} # Email администратора (можно переопределить через ADMIN_EMAIL)
  password: ${ADMIN_PASSWORD:admin123}    # Пароль администратора (можно переопределить через ADMIN_PASSWORD)

finance:
  kafka:
    large-expense-threshold: 50000  # порог крупной траты в рублях

springdoc:
  api-docs:
    enabled: true
  paths-to-match: /empty
  swagger-ui:
    url: /v3/api-docs-static
    path: /swagger-ui.html