spring:
  # Конфигурация PostgreSQL БД для dev
  datasource:
    url: jdbc:postgresql://finance-db:5432/${POSTGRES_DB} #//localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      initialization-fail-timeout: -1   # Не падает при ошибке инициализации пула

  # JPA конфигурация для dev
  jpa:
    hibernate:
      ddl-auto: update                  # Автоматически добавляет новые колонки

  # Redis конфигурация для кэширования
  redis:
    port: redis #${REDIS_PORT}
    database: 1

  # Kafka конфигурация
  kafka:
    bootstrap-servers: kafka:9092 #localhost:29092
    consumer:
      group-id: financeTrackerGroupDev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.yandex.finance_tracker"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1

   # Логирование для dev окружения
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application-dev.log